name: Build simc.exe

on:
  push:
    branches:
      - midnight
  workflow_dispatch:

jobs:
  build_windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: "latest"

      - name: Setup VS environment
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Configure with CMake
        run: |
          cmake -B build -S . -G "Ninja" -DCMAKE_BUILD_TYPE=Release

      - name: Build simc
        run: cmake --build build --config Release --target simc

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: simc-exe
          path: build/Release/simc.exe
